
---
name: terraform-ci

on:
  pull_request:
    branches: [main]

env:
  TEMPLATE_REPOSITORY: telekom-mms/terraform-template

jobs:
  call-terraform-ci:
    if: github.repository != '$TEMPLATE_REPOSITORY'
    uses: telekom-mms/.github/.github/workflows/terraform-ci.yml@eff2548e73bca7b1f2addec32eb23643107181b5 # main
    with:
      working-directory: examples/vpc-basic
