
---
name: update-changelog

on:
  pull_request:
    types: [closed]

env:
  TEMPLATE_REPOSITORY: telekom-mms/terraform-template

jobs:
  call-update-changelog:
    if: github.repository != '$TEMPLATE_REPOSITORY'
    uses: telekom-mms/.github/.github/workflows/update-changelog.yml@313967c681dc08d00173a149633302f10b129dfc # main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
